import { Schema } from 'mongoose'

export const FoodSchema: Schema = new Schema({
  id: { type: Number, required: true, unique: true },
  name: { type: String, required: true, unique: true },
  ediblePortion: { type: Number, required: true },
  energy: { type: Number, required: true },
  water: { type: Number, required: true },
  protein: { type: Number, required: true },
  animalProtein: { type: Number, required: true },
  vegetalProtein: { type: Number, required: true },
  lipids: { type: Number, required: true },
  saturatedFat: { type: Number, required: true },
  monounsaturatedFat: { type: Number, required: true },
  polyunsaturatedFat: { type: Number, required: true },
  cholesterol: { type: Number, required: true },
  glycide: { type: Number, required: true },
  sugar: { type: Number, required: true },
  polysaccharide: { type: Number, required: true },
  fiber: { type: Number, required: true },
  ethanol: { type: Number, required: true },
  sodium: { type: Number, required: true },
  potassium: { type: Number, required: true },
  calcium: { type: Number, required: true },
  magnesium: { type: Number, required: true },
  phosphorus: { type: Number, required: true },
  iron: { type: Number, required: true },
  zinc: { type: Number, required: true },
  vitaminA: { type: Number, required: true },
  retinoids: { type: Number, required: true },
  carotenoids: { type: Number, required: true },
  vitaminD: { type: Number, required: true },
  vitaminE: { type: Number, required: true },
  thiamine: { type: Number, required: true },
  riboflavin: { type: Number, required: true },
  niacin: { type: Number, required: true },
  vitaminB6: { type: Number, required: true },
  folicAcid: { type: Number, required: true },
  vitaminB12: { type: Number, required: true },
  vitaminC: { type: Number, required: true },
  group: { type: String, required: true },
  subGroup: { type: String, required: true }
})
