export class CreateFoodDto {
  id: number
  name: string
  ediblePortion: number
  energy: number
  water: number
  protein: number
  animalProtein: number
  vegetalProtein: number
  lipids: number
  saturatedFat: number
  monounsaturatedFat: number
  polyunsaturatedFat: number
  cholesterol: number
  glycide: number
  sugar: number
  polysaccharide: number
  fiber: number
  ethanol: number
  sodium: number
  potassium: number
  calcium: number
  magnesium: number
  phosphorus: number
  iron: number
  zinc: number
  vitaminA: number
  retinoids: number
  carotenoids: number
  vitaminD: number
  vitaminE: number
  thiamine: number
  riboflavin: number
  niacin: number
  vitaminB6: number
  folicAcid: number
  vitaminB12: number
  vitaminC: number
  group: string
  subGroup: string
}
